/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AS-Website-Gateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AS-Website-Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AS-Website-Static": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ContactFormEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
  }
}

import "sst"
export {}