name: Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "preview"

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Installing project dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Check Types
        run: |
          npm run check
      - name: Format Check
        run: |
          npm run format:check
      - name: Run Tests
        run: |
          npm run test
      - name: Build
        run: |
          npm run build:ci
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TOKEN: ${{ secrets.DATABASE_TOKEN }}
      # TODO: restore storybook
      # - name: Storybook
      #   run: |
      #     npm run storybook:build
